{% set name = "conda-anaconda-tos" %}

package:
  name: {{ name|lower }}
  # VERSION_OVERRIDE is used by the canary release workflow
  version: {{ os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - git  # for source/git_url above
  host:
    - python >=3.9
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.9
    - conda >=24.11
    - rich
    - pydantic

test:
  requires:
    - pip
    - conda
  imports:
    - conda_anaconda_tos
    - conda_anaconda_tos.plugin
    - conda_anaconda_tos.api
  commands:
    - pip check
    - conda tos --version

about:
  home: https://github.com/anaconda/{{ name }}
  summary: Anaconda Terms of Service conda plugin
  description: Conda subcommand to view, accept, and interact with a channel's Terms of Service (ToS).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kenodegard
    - jezdez
