{% set name = "anaconda-conda-tos" %}

package:
  name: {{ name|lower }}
  # VERSION_OVERRIDE is used by the canary release workflow
  version: {{ os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools-scm
  run:
    - python >=3.9
    - conda >=23.9.0
    - rich
    - pydantic

test:
  imports:
    - anaconda_conda_tos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anaconda/{{ name }}
  summary: Conda subcommand to view, accept, and interact with a channel's Terms of Service (ToS).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kenodegard
