{% set name = "anaconda-conda-tos" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ???

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
  run:
    - python >=3.8.1,<4.0.0
    - conda

test:
  imports:
    - anaconda_conda_tos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anaconda/{{ name }}
  summary: Conda subcommand to view, accept, and interact with a channel's Terms of Service (ToS).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kenodegard
