repos:
  # generic verification and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: |
          (?x)^(
            recipe/meta.yaml
          )
      - id: check-json
      # catch git merge/rebase problems
      - id: check-merge-conflict
  # Python verification and formatting
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      # auto inject license blurb
      - id: insert-license
        files: \.py$
        args: [--license-filepath, .github/disclaimer.txt, --no-extra-eol, --use-current-year]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      # auto format Python codes within docstrings
      - id: blacken-docs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      # lint & attempt to correct failures (e.g. pyupgrade)
      - id: ruff
        args: [--fix]
      # compatible replacement for black
      - id: ruff-format
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --trailing-commas]
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        # ruamel.yaml doesn't line wrap correctly (?) so set width to 1M to avoid issues
        args: [--mapping=2, --offset=2, --sequence=4, --width=1000000, --implicit_start]
        exclude: |
          (?x)^(
            recipe/meta.yaml
          )
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      # verify github syntaxes
      - id: check-github-workflows
      - id: check-renovate
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
  - repo: meta
    # see https://pre-commit.com/#meta-hooks
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: git-diff
        name: git diff
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
