name: Feature Request
description: Suggest an idea for conda-anaconda-tos
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: A clear and concise description of what problem this feature would solve.
      placeholder: I'm always frustrated when [...] or It would improve user experience to [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution here.
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives you've considered.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be valuable.
      placeholder: In my workflow, I need to...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how to implement this feature, please share them here.
